# !!! Um das automatische Installieren zu ermöglichen muss das oxideshop_composer_plugin gepachted werden
# https://github.com/OXID-eSales/oxideshop_composer_plugin/blob/87fcaaba356c60bd5c0edf23a9c643809da68165/src/Installer/Package/AbstractPackageInstaller.php#L199
# Von `N` auf `Y`

stages:
- deploy

deploy_to_nrsweb08:
  stage: deploy
  only:
    - 'dev2.x'
  script:
    - 'ssh nrdeploy@172.16.16.23 "cd /var/wwwfile/36520; composer require arvato/afterpay dev-dev2.x -n"'
