[{if $sPaymentID == "afterpayinstallment"}]
    [{include file="wave/page/checkout/inc/payment_afterpayinstallment.tpl"}]
[{elseif $sPaymentID == "afterpaydebitnote"}]
    [{include file="wave/page/checkout/inc/payment_afterpaydebitnote.tpl"}]
[{elseif $sPaymentID == "afterpayinvoice"}]
    [{include file="wave/page/checkout/inc/payment_afterpayinvoice.tpl"}]
[{else}]
    [{$smarty.block.parent}]
[{/if}]