<?php

$sLangName = 'English';

$aLang = [
    'charset' => 'UTF-8',

    'ORDER_OVERVIEW_APBIRTHDAY' => 'Birthdate',
    'ORDER_OVERVIEW_APPHONE'    => 'Phone',
    'ORDER_OVERVIEW_APFON'      => 'Phone',
    'ORDER_OVERVIEW_APSSN'      => 'SSN',

    'ORDER_AFTERPAY_ORDERED_AMOUNT'  => 'Ordered amount',
    'ORDER_AFTERPAY_CAPTURED_AMOUNT' => 'Of which captured amount',
    'ORDER_AFTERPAY_REFUNDED_AMOUNT' => 'Of which refunded amount',
    'ORDER_AFTERPAY_VOIDED_AMOUNT'   => 'Of which voided amount',

    'ORDER_AFTERPAY_TITLE_LISTOFALLITEMS' => 'List of all ordered items',
    'ORDER_AFTERPAY_TITLE_CAPTUREPAYMENT' => 'Capture pending payments',
    'ORDER_AFTERPAY_TITLE_REFUNDPAYMENT'  => 'Refund captured payments',
    'ORDER_AFTERPAY_TITLE_REFUNDPAYMENTFREE'  => 'Refund captured payments - Enter any amount',

    'ORDER_AFTERPAY_TITLE_VOIDPAYMENT'    => 'Cancel payment reservations',

    'ORDER_AFTERPAY_CATEGORY_MAIN_HELP'      => 'Here should be the main category shown, with which the article is connected',
    'ORDER_AFTERPAY_MAIN_CATEGORY'           => 'Main category',

    'SHOP_MODULE_GROUP_arvatoAfterpayGeneral'               => 'General Settings',
    'SHOP_MODULE_arvatoAfterpayApiDefaultShippingCompany'   => 'Default Shipping Company',
    'HELP_SHOP_MODULE_arvatoAfterpayApiDefaultShippingCompany'   => 'Setting for shipping capture: After an order has been captured its shipping can be captured too. The tracking code and used shipping company can then be input.',
    'SHOP_MODULE_arvatoAfterpayApiDefaultRefundDescription' => 'Default refund description',
    'HELP_SHOP_MODULE_arvatoAfterpayApiDefaultRefundDescription' => 'Will be used as default if no other refund reason/description was entered.',
    'SHOP_MODULE_arvatoAfterpayRiskChannelType'             => 'Risk management - ChannelType',
    'HELP_SHOP_MODULE_arvatoAfterpayRiskChannelType'        => 'Relevant for risk management: What kind of channel type should be sent in afterpay requests. Default "Internet".',
    'SHOP_MODULE_arvatoAfterpayRiskDeliveryType'            => 'Risk management - DeliveryType',
    'HELP_SHOP_MODULE_arvatoAfterpayRiskDeliveryType'       => 'Relevant for risk management: What kind of delivery type should be sent in afterpay requests. Default "Normal".',
    'SHOP_MODULE_arvatoAfterpayManufacturerInDescription'              => 'Marke',
    'HELP_SHOP_MODULE_arvatoAfterpayManufacturerInDescription'         => 'Should the manufacturer or vendor title be prepended to the article title on afterpay requests',
    'SHOP_MODULE_arvatoAfterpayManufacturerInDescription_no'           => 'no',
    'SHOP_MODULE_arvatoAfterpayManufacturerInDescription_manufacturer' => 'oxmanufacturer',
    'SHOP_MODULE_arvatoAfterpayManufacturerInDescription_vendor'       => 'oxvendor',
    'SHOP_MODULE_arvatoAfterpayVariantInDescription'                   => 'Add variant to title',
    'HELP_SHOP_MODULE_arvatoAfterpayVariantInDescription'              => 'Should the variant selection appended to the article title on afterpay requests',
    'SHOP_MODULE_arvatoAfterpayVariantInDescription_yes'               => 'Yes',
    'SHOP_MODULE_arvatoAfterpayVariantInDescription_no'                => 'No',
    'SHOP_MODULE_arvatoAfterpayLogo'          => 'Logo displayed in checkout',
    'HELP_SHOP_MODULE_arvatoAfterpayLogo'     => 'All possible logos are listed <a target="_blank" href="https://developer.afterpay.io/documentation/logo-and-visual-guidelines/">here</a>.',
    'SHOP_MODULE_arvatoAfterpayLogo_Checkout' => 'Checkout',
    'SHOP_MODULE_arvatoAfterpayLogo_'         => 'Original',
    'SHOP_MODULE_arvatoAfterpayLogo_Black'    => 'Black',
    'SHOP_MODULE_arvatoAfterpayLogo_White'    => 'White',
    'SHOP_MODULE_arvatoAfterpayLogo_Grey'     => 'Grey',
    'SHOP_MODULE_arvatoAfterpayExcludedArticleNr'     => 'Excluded article numbers',
    'HELP_SHOP_MODULE_arvatoAfterpayExcludedArticleNr'     => 'All entered article numbers are excluded from payment with Afterpay. <br> Please separate the article numbers with a comma.',

    'SHOP_MODULE_GROUP_arvatoAfterpayApi' => 'API Settings',
    'SHOP_MODULE_arvatoAfterpayApiUrl'    => 'API Url',

    'SHOP_MODULE_arvatoAfterpayApiKeyDE'            => 'API key GER',
    'SHOP_MODULE_arvatoAfterpayApiKeyDEInstallment' => 'API key for installments GER',
    'SHOP_MODULE_arvatoAfterpayApiKeyAT'            => 'API key AUT',
    'SHOP_MODULE_arvatoAfterpayApiKeyATInstallment' => 'API key for installments AUT',
    'SHOP_MODULE_arvatoAfterpayApiKeyCH'            => 'API key CH',
    'SHOP_MODULE_arvatoAfterpayApiKeyNL'            => 'API key NL',
    'SHOP_MODULE_arvatoAfterpayApiKeyBE'            => 'API key BE',

    'SHOP_MODULE_arvatoAfterpayApiMode'         => 'API mode',
    'SHOP_MODULE_arvatoAfterpayApiMode_live'    => 'Live',
    'SHOP_MODULE_arvatoAfterpayApiMode_partner' => 'Partner Test',
    'SHOP_MODULE_arvatoAfterpayApiMode_sandbox' => 'Sandbox',

    'SHOP_MODULE_arvatoAfterpayApiSandboxUrl'              => 'Sandbox API URL',
    'SHOP_MODULE_arvatoAfterpayApiSandboxKeyDE'            => 'Sandbox API key GER',
    'SHOP_MODULE_arvatoAfterpayApiSandboxKeyDEInstallment' => 'Sandbox API key for installments GER',
    'SHOP_MODULE_arvatoAfterpayApiSandboxKeyAT'            => 'Sandbox API key AUT',
    'SHOP_MODULE_arvatoAfterpayApiSandboxKeyATInstallment' => 'Sandbox API key for installments AUT',
    'SHOP_MODULE_arvatoAfterpayApiSandboxKeyCH'            => 'Sandbox API key CH',
    'SHOP_MODULE_arvatoAfterpayApiSandboxKeyNL'            => 'Sandbox API key NL',
    'SHOP_MODULE_arvatoAfterpayApiSandboxKeyBE'            => 'Sandbox API key BE',

    'SHOP_MODULE_arvatoAfterpayApiPartnerUrl'              => 'Partner Test API URL',
    'SHOP_MODULE_arvatoAfterpayApiPartnerKeyDE'            => 'Partner Test API key GER',
    'SHOP_MODULE_arvatoAfterpayApiPartnerKeyDEInstallment' => 'Partner Test API key for installments GER',
    'SHOP_MODULE_arvatoAfterpayApiPartnerKeyAT'            => 'Partner Test API key AUT',
    'SHOP_MODULE_arvatoAfterpayApiPartnerKeyATInstallment' => 'Partner Test API key for installments AUT',
    'SHOP_MODULE_arvatoAfterpayApiPartnerKeyCH'            => 'Partner Test API key CH',
    'SHOP_MODULE_arvatoAfterpayApiPartnerKeyNL'            => 'Partner Test API key NL',
    'SHOP_MODULE_arvatoAfterpayApiPartnerKeyBE'            => 'Partner Test API key BE',

    'HELP_SHOP_MODULE_arvatoAfterpayApiMode'             => 'API mode: Defines which of the three sets of settings (live, sandbox, partner test) should be used when making API requests.',
    'HELP_SHOP_MODULE_arvatoAfterpayApiRequestLogging'   => 'Enables logging of request and response. Log can be found in the OXID logging directory: AFTERPAY.log',
    'HELP_SHOP_MODULE_arvatoAfterpayApiUrl'              => 'Sets the URL for the API.',
    'HELP_SHOP_MODULE_arvatoAfterpayApiKeyDE'            => 'Sets the API key to be used for the respective country.',
    'HELP_SHOP_MODULE_arvatoAfterpayApiKeyDEInstallment' => 'Sets the API key to be used for the respective country (only for installments).',

    'SHOP_MODULE_arvatoAfterpayApiRequestLogging'      => 'API request logging',
    'arvato_afterpay_controllers_admin_order_afterpay' => 'AfterPay',
    'AFTERPAY_ONLY_FOR_AFTERPAY_PAYMENT'               => 'This order was not paid via AfterPay',
    'ORDER_OVERVIEW_APDEBITBANKACCOUNT'                => 'IBAN',
    'ORDER_OVERVIEW_APINSTALLMENTBANKACCOUNT'          => 'IBAN',
    'ORDER_OVERVIEW_APINSTALLMENTBANKCODE'             => 'BIC',
    'ORDER_OVERVIEW_AFTERPAYINSTALLMENTPROFILEID'      => 'Installment profile',

    'SHOP_MODULE_GROUP_arvatoAfterpayRequiredFields'          => 'Required fields',
    'SHOP_MODULE_arvatoAfterpayInvoiceRequiresBirthdate'      => 'Invoice requires birthdate',
    'SHOP_MODULE_arvatoAfterpayDebitRequiresBirthdate'        => 'Debit requires birthdate',
    'SHOP_MODULE_arvatoAfterpayInstallmentsRequiresBirthdate' => 'Installments require birthdate',
    'SHOP_MODULE_arvatoAfterpayInvoiceRequiresSSN'            => 'Invoice requires SSN',
    'SHOP_MODULE_arvatoAfterpayDebitRequiresSSN'              => 'Debit requires SSN',
    'SHOP_MODULE_arvatoAfterpayInstallmentsRequiresSSN'       => 'Installments require SSN',
    'SHOP_MODULE_arvatoAfterpayInvoiceRequiresFon'            => 'Invoice requires phone number',
    'SHOP_MODULE_arvatoAfterpayDebitRequiresFon'              => 'Debit requires phone number',
    'SHOP_MODULE_arvatoAfterpayInstallmentsRequiresFon'       => 'Installments require phone number',

    'SHOP_MODULE_GROUP_arvatoAfterpayProfileTracking'           => 'Profile Tracking',
    'SHOP_MODULE_arvatoAfterpayProfileTrackingEnabled'          => 'Profile tracking',
    'SHOP_MODULE_arvatoAfterpayProfileTrackingEnabled_inactive' => 'Inactive',
    'SHOP_MODULE_arvatoAfterpayProfileTrackingEnabled_mandatory'=> 'Required',
    'SHOP_MODULE_arvatoAfterpayProfileTrackingEnabled_optional' => 'Optional',
    'SHOP_MODULE_arvatoAfterpayProfileTrackingUrl'              => 'Profile tracking URL',
    'SHOP_MODULE_arvatoAfterpayProfileTrackingId'               => 'Profile tracking client ID',
    'HELP_SHOP_MODULE_arvatoAfterpayProfileTrackingEnabled'     => 'Activates the profile tracking on payment selection page',
    'HELP_SHOP_MODULE_arvatoAfterpayProfileTrackingUrl'         => 'Profile tracking requests are sent to this URL',
    'HELP_SHOP_MODULE_arvatoAfterpayProfileTrackingId'          => 'ID used for profile tracking',

    'HELP_ARTICLE_MAIN_AAPPRODUCTGROUP' => 'Define the AfterPay product group. If you leave this field empty, the shop will attempt to find the product group based on the assigned categories. The bracket shows the found and submitted product group.',
    'ORDER_AFTERPAY_FORCAPTURENO'       => 'for capture number',

    'ORDER_AFTERPAY_PROMPT_REALLYVOID'   => 'Void reservation? This cannot be undone. The order is then closed for further administration',
    'ORDER_AFTERPAY_PROMPT_REALLYREFUND' => 'Refund captured money? This cannot be undone.',

    'ORDER_AFTERPAY_TITLE_CAPTUREDELIVERY' => 'Capture delivery information',

    'AFTERPAY_ORDER_ALREADY_VOIDED' => 'This order contains cancelled payments and hence cannot be edited.',

    //Menu
    'ARVATOMODULES'                     => 'Arvato Module',
    'AFTERPAY_TITLE'                    => 'Afterpay',
    'AFTERPAY_SETTINGS'                 => 'Settings',
    'AFTERPAY_SETTINGS_TERMSPRIVACY'    => 'T&C & Privacy',
    'AFTERPAY_SAVED'                    => 'Settings were saved',
    'AFTERPAY_SAVE_BUTTON'              => 'Save',

    'AFTERPAY_COUNTRY_REQUIREDFIELDS_Germany'                       => 'Germany',
    'AFTERPAY_COUNTRY_REQUIREDFIELDS_Austria'                       => 'Austria',
    'AFTERPAY_COUNTRY_REQUIREDFIELDS_Switzerland'                   => 'Switzerland',
    'AFTERPAY_COUNTRY_REQUIREDFIELDS_Netherlands'                   => 'Netherlands',
    'AFTERPAY_COUNTRY_REQUIREDFIELDS_Belgium'                       => 'Belgium',
    'AFTERPAY_COUNTRY_REQUIREDFIELDS_Sweden'                        => 'Sweden',
    'AFTERPAY_COUNTRY_REQUIREDFIELDS_Norway'                        => 'Norway',
    'AFTERPAY_COUNTRY_REQUIREDFIELDS_Finland'                       => 'Finland',
    'AFTERPAY_COUNTRY_REQUIREDFIELDS_Denmark'                       => 'Denmark',
    'SHOP_MODULE_arvatoAfterpayRequireFieldsExplanation'            => 'The following checkboxes define which fields are required to be filled or checked by the user to be able to proceed with payment',
    'HELP_SHOP_MODULE_arvatoAfterpayHorizonID'                      => 'The horizon ID is necessary for building the URLs for the privacy and T&C page',

    'SHOP_MODULE_arvatoAfterpayInvoiceRequiresStreetNumber'             => 'Invoice requires Street Number',
    'SHOP_MODULE_arvatoAfterpayDebitRequiresStreetNumber'               => 'Debit requires Street Number',
    'SHOP_MODULE_arvatoAfterpayInstallmentsRequiresStreetNumber'        => 'Installments require Street Number',

    'SHOP_MODULE_arvatoAfterpayInvoiceRequiresSalutation'             => 'Invoice requires Salutation',
    'SHOP_MODULE_arvatoAfterpayDebitRequiresSalutation'               => 'Bankeinzug erfordert Salutation',
    'SHOP_MODULE_arvatoAfterpayInstallmentsRequiresSalutation'        => 'Installments require Salutation',

    'SHOP_MODULE_arvatoAfterpayHorizonID'           => 'Horizon-ID',
    'SHOP_MODULE_arvatoAfterpayRequiresSalutation'        => 'Salutation',
    'SHOP_MODULE_arvatoAfterpayRequiresSSN'               => 'SSN',
    'SHOP_MODULE_arvatoAfterpayRequiresPhone'        => 'Phone',
    'SHOP_MODULE_arvatoAfterpayRequiresBirthdate'        => 'Birthday',
    'SHOP_MODULE_arvatoAfterpayRequiresStreetNumber'        => 'Street number',
    'SHOP_MODULE_arvatoAfterpayRequiresPrivacy'        => 'Privacy',
    'SHOP_MODULE_arvatoAfterpayRequiresTC'        => 'TC',

    'SHOP_MODULE_arvatoAfterpayRequireFields'       => 'Fields',
    'SHOP_MODULE_arvatoAfterpayInvoice'             => 'Invoice',
    'SHOP_MODULE_arvatoAfterpayDebit'               => 'Debit',
    'SHOP_MODULE_arvatoAfterpayInstallments'        => 'Installment',

];
