<?php

$sLangName = 'Deutsch';

$aLang = [
    'charset' => 'UTF-8',

    'ORDER_OVERVIEW_APBIRTHDAY' => 'Geburtstag',
    'ORDER_OVERVIEW_APPHONE'    => 'Telefon',
    'ORDER_OVERVIEW_APSSN'      => 'SSN',

    'ORDER_AFTERPAY_ORDERED_AMOUNT'  => 'Bestellte Anzahl',
    'ORDER_AFTERPAY_CAPTURED_AMOUNT' => 'Davon eingezogene Anzahl',
    'ORDER_AFTERPAY_REFUNDED_AMOUNT' => 'Davon erstattete Anzahl',
    'ORDER_AFTERPAY_VOIDED_AMOUNT'   => 'Davon stornierte Anzahl',

    'ORDER_AFTERPAY_TITLE_LISTOFALLITEMS'    => 'Gesamtliste aller bestellter Artikel',
    'ORDER_AFTERPAY_TITLE_CAPTUREPAYMENT'    => 'Reservierte Zahlung einziehen',
    'ORDER_AFTERPAY_TITLE_REFUNDPAYMENT'     => 'Eingezogene Zahlung erstatten',
    'ORDER_AFTERPAY_TITLE_REFUNDPAYMENTFREE' => 'Eingezogene Zahlung erstatten - Frei wählbarer Betrag',
    'ORDER_AFTERPAY_TITLE_VOIDPAYMENT'       => 'Reservierte Zahlung freigeben',

    'ORDER_AFTERPAY_CATEGORY_MAIN_HELP'      => 'Hier wird die Hauptkategorie angezeigt, mit der der Artikel verknüpft wird, falls eine Hauptkategorie in der Datenbank existiert.',
    'ORDER_AFTERPAY_MAIN_CATEGORY'           => 'Hauptkategorie',

    'SHOP_MODULE_GROUP_arvatoAfterpayGeneral'               => 'Allgemeine Einstellungen',
    'SHOP_MODULE_arvatoAfterpayApiDefaultShippingCompany'   => 'Standard Versandunternehmen',
    'SHOP_MODULE_arvatoAfterpayApiDefaultRefundDescription' => 'Standard Rückerstattungs-Beschreibung',
    'SHOP_MODULE_arvatoAfterpayRiskChannelType'             => 'Risikosteuerung - ChanelType',
    'SHOP_MODULE_arvatoAfterpayRiskDeliveryType'            => 'Risikosteuerung - DeliveryType',
    'SHOP_MODULE_arvatoAfterpayManufacturerInDescription'              => 'Marke',
    'SHOP_MODULE_arvatoAfterpayManufacturerInDescription_no'           => 'nichts übergeben',
    'SHOP_MODULE_arvatoAfterpayManufacturerInDescription_manufacturer' => 'oxmanufacturer',
    'SHOP_MODULE_arvatoAfterpayManufacturerInDescription_vendor'       => 'oxvendor',
    'SHOP_MODULE_arvatoAfterpayVariantInDescription'                   => 'Variante mit übergeben',
    'SHOP_MODULE_arvatoAfterpayVariantInDescription_yes'               => 'Ja',
    'SHOP_MODULE_arvatoAfterpayVariantInDescription_no'                => 'Nein',
    'SHOP_MODULE_arvatoAfterpayLogo'          => 'Im Checkout angezeigtes Logo',
    'HELP_SHOP_MODULE_arvatoAfterpayLogo'     => 'Die verschiedenen Optionen sind <a target="_blank" href="https://developer.afterpay.io/documentation/logo-visual-guidelines/">hier</a> aufgelistet.',
    'SHOP_MODULE_arvatoAfterpayLogo_Checkout' => 'Checkout',
    'SHOP_MODULE_arvatoAfterpayLogo_'         => 'Original',
    'SHOP_MODULE_arvatoAfterpayLogo_Black'    => 'Schwarz',
    'SHOP_MODULE_arvatoAfterpayLogo_White'    => 'Weiß',
    'SHOP_MODULE_arvatoAfterpayLogo_Grey'     => 'Grau',
    'SHOP_MODULE_arvatoAfterpayExcludedArticleNr'     => 'Ausgeschlossene Artikelnummer',
    'HELP_SHOP_MODULE_arvatoAfterpayExcludedArticleNr'     => 'Alle eingetragenen Artikelnummern sind von der Bezahlung mit Afterpay ausgeschlossen <br> Bitte unbedingt die Artikelnummern mit Komma trennen',

    'SHOP_MODULE_GROUP_arvatoAfterpayApi' => 'API Einstellungen',
    'SHOP_MODULE_arvatoAfterpayApiUrl'    => 'API Url',

    'SHOP_MODULE_arvatoAfterpayApiKeyDE'            => 'API Schlüssel DE',
    'SHOP_MODULE_arvatoAfterpayApiKeyDEInstallment' => 'API Schlüssel für Ratenkauf DE',
    'SHOP_MODULE_arvatoAfterpayApiKeyAT'            => 'API Schlüssel AT',
    'SHOP_MODULE_arvatoAfterpayApiKeyATInstallment' => 'API Schlüssel für Ratenkauf AT',
    'SHOP_MODULE_arvatoAfterpayApiKeyCH'            => 'API Schlüssel CH',
    'SHOP_MODULE_arvatoAfterpayApiKeyNL'            => 'API Schlüssel NL',
    'SHOP_MODULE_arvatoAfterpayApiKeyBE'            => 'API Schlüssel BE',

    'SHOP_MODULE_arvatoAfterpayApiMode'         => 'API Modus',
    'SHOP_MODULE_arvatoAfterpayApiMode_live'    => 'Live',
    'SHOP_MODULE_arvatoAfterpayApiMode_partner' => 'Partner Test',
    'SHOP_MODULE_arvatoAfterpayApiMode_sandbox' => 'Sandbox',

    'SHOP_MODULE_arvatoAfterpayApiSandboxUrl'              => 'Sandbox API URL',
    'SHOP_MODULE_arvatoAfterpayApiSandboxKeyDE'            => 'Sandbox API Schlüssel DE',
    'SHOP_MODULE_arvatoAfterpayApiSandboxKeyDEInstallment' => 'Sandbox API Schlüssel für Ratenkauf DE',
    'SHOP_MODULE_arvatoAfterpayApiSandboxKeyAT'            => 'Sandbox API Schlüssel AT',
    'SHOP_MODULE_arvatoAfterpayApiSandboxKeyATInstallment' => 'Sandbox API Schlüssel für Ratenkauf AT',
    'SHOP_MODULE_arvatoAfterpayApiSandboxKeyCH'            => 'Sandbox API Schlüssel CH',
    'SHOP_MODULE_arvatoAfterpayApiSandboxKeyNL'            => 'Sandbox API Schlüssel NL',
    'SHOP_MODULE_arvatoAfterpayApiSandboxKeyBE'            => 'Sandbox API Schlüssel BE',

    'SHOP_MODULE_arvatoAfterpayApiPartnerUrl'              => 'Partner Test API URL',
    'SHOP_MODULE_arvatoAfterpayApiPartnerKeyDE'            => 'Partner Test API Schlüssel DE',
    'SHOP_MODULE_arvatoAfterpayApiPartnerKeyDEInstallment' => 'Partner Test API Schlüssel für Ratenkauf DE',
    'SHOP_MODULE_arvatoAfterpayApiPartnerKeyAT'            => 'Partner Test API Schlüssel AT',
    'SHOP_MODULE_arvatoAfterpayApiPartnerKeyATInstallment' => 'Partner Test API Schlüssel für Ratenkauf AT',
    'SHOP_MODULE_arvatoAfterpayApiPartnerKeyCH'            => 'Partner Test API Schlüssel CH',
    'SHOP_MODULE_arvatoAfterpayApiPartnerKeyNL'            => 'Partner Test API Schlüssel NL',
    'SHOP_MODULE_arvatoAfterpayApiPartnerKeyBE'            => 'Partner Test API Schlüssel BE',

    'SHOP_MODULE_arvatoAfterpayApiRequestLogging'      => 'Api Anfragenprotokollierung',
    'arvato_afterpay_controllers_admin_order_afterpay' => 'AfterPay',
    'AFTERPAY_ONLY_FOR_AFTERPAY_PAYMENT'               => 'Diese Bestellung wurde nicht mit AfterPay bezahlt',
    'ORDER_OVERVIEW_APDEBITBANKACCOUNT'                => 'IBAN',
    'ORDER_OVERVIEW_APINSTALLMENTBANKACCOUNT'          => 'IBAN',
    'ORDER_OVERVIEW_APINSTALLMENTBANKCODE'             => 'BIC',
    'ORDER_OVERVIEW_AFTERPAYINSTALLMENTPROFILEID'      => 'Ratenzahlungsprofil',

    'SHOP_MODULE_GROUP_arvatoAfterpayRequiredFields'          => 'Pflichtfelder',
    'SHOP_MODULE_arvatoAfterpayInvoiceRequiresBirthdate'      => 'Rechnung erfordert Geburtsdatum',
    'SHOP_MODULE_arvatoAfterpayDebitRequiresBirthdate'        => 'Bankeinzug erfordert Geburtsdatum',
    'SHOP_MODULE_arvatoAfterpayInstallmentsRequiresBirthdate' => 'Ratenzahlung erfordert Geburtsdatum',
    'SHOP_MODULE_arvatoAfterpayInvoiceRequiresSSN'            => 'Rechnung erfordert SSN',
    'SHOP_MODULE_arvatoAfterpayDebitRequiresSSN'              => 'Bankeinzug erfordert SSN',
    'SHOP_MODULE_arvatoAfterpayInstallmentsRequiresSSN'       => 'Ratenzahlung erfordert SSN',
    'SHOP_MODULE_arvatoAfterpayInvoiceRequiresFon'            => 'Rechnung erfordert Telefonnummer',
    'SHOP_MODULE_arvatoAfterpayDebitRequiresFon'              => 'Bankeinzug erfordert Telefonnummer',
    'SHOP_MODULE_arvatoAfterpayInstallmentsRequiresFon'       => 'Ratenzahlung erfordert Telefonnummer',

    'SHOP_MODULE_GROUP_arvatoAfterpayProfileTracking'           => 'Profile Tracking (Browsergestützte Betrugserkennung)',
    'SHOP_MODULE_arvatoAfterpayProfileTrackingEnabled'          => 'Profile Tracking',
    'SHOP_MODULE_arvatoAfterpayProfileTrackingEnabled_inactive' => 'Inaktiv',
    'SHOP_MODULE_arvatoAfterpayProfileTrackingEnabled_mandatory'=> 'Pflicht',
    'SHOP_MODULE_arvatoAfterpayProfileTrackingEnabled_optional' => 'Optional',
    'SHOP_MODULE_arvatoAfterpayProfileTrackingUrl'              => 'Profile Tracking URL',
    'SHOP_MODULE_arvatoAfterpayProfileTrackingId'               => 'Profile Tracking Client ID',

    'HELP_ARTICLE_MAIN_AAPPRODUCTGROUP' => 'Definieren Sie die AfterPay-Produktgruppe des Artikels. Lassen Sie das Feld leer, so wird versucht die Produktgruppe anhand der zugeordneten Kategorien zu beziehen. In Klammern steht die übertragene Produktgruppe.',
    'ORDER_AFTERPAY_FORCAPTURENO'       => 'auf Capture-Nummer',
    'ORDER_AFTERPAY_PROMPT_REALLYVOID'     => 'Reservierung freigeben? Das kann nicht rückgängig gemacht werden. Die Bestellung kann danach nicht weiter bearbeitet werden.',
    'ORDER_AFTERPAY_PROMPT_REALLYREFUND'   => 'Zahlung erstatten? Das kann nicht rückgängig gemacht werden.',
    'ORDER_AFTERPAY_TITLE_CAPTUREDELIVERY' => 'Versand erfassen',

    'AFTERPAY_ORDER_ALREADY_VOIDED' => 'Diese Bestellung enthält stornierte Zahlungen und kann deshalb nicht weiter bearbeitet werden.',

    //Menu
    'ARVATOMODULES'                     => 'Arvato Module',
    'AFTERPAY_TITLE'                    => 'Afterpay',
    'AFTERPAY_SETTINGS'                 => 'Einstellungen',
    'AFTERPAY_SETTINGS_TERMSPRIVACY'    => 'AGB & Datenschutz',
    'AFTERPAY_SAVED'                    => 'Einstellungen wurden gespeichert',
    'AFTERPAY_SAVE_BUTTON'              => 'Speichern',

    'AFTERPAY_COUNTRY_REQUIREDFIELDS_Germany'                     => 'Deutschland',
    'AFTERPAY_COUNTRY_REQUIREDFIELDS_Austria'                     => 'Österreich',
    'AFTERPAY_COUNTRY_REQUIREDFIELDS_Switzerland'                 => 'Schweiz',
    'AFTERPAY_COUNTRY_REQUIREDFIELDS_Netherlands'                 => 'Niederlande',
    'AFTERPAY_COUNTRY_REQUIREDFIELDS_Belgium'                     => 'Belgien',
    'AFTERPAY_COUNTRY_REQUIREDFIELDS_Sweden'                      => 'Schweden',
    'AFTERPAY_COUNTRY_REQUIREDFIELDS_Norway'                      => 'Norwegen',
    'AFTERPAY_COUNTRY_REQUIREDFIELDS_Finland'                     => 'Finnland',
    'AFTERPAY_COUNTRY_REQUIREDFIELDS_Denmark'                     => 'Dänemark',

    'SHOP_MODULE_arvatoAfterpayInvoiceRequiresStreetNumber'             => 'Rechnung erfordert Hausnummer',
    'SHOP_MODULE_arvatoAfterpayDebitRequiresStreetNumber'               => 'Bankeinzug erfordert Hausnummer',
    'SHOP_MODULE_arvatoAfterpayInstallmentsRequiresStreetNumber'        => 'Ratenzahlung erfordert Hausnummer',

    'SHOP_MODULE_arvatoAfterpayInvoiceRequiresSalutation'             => 'Rechnung erfordert Anrede',
    'SHOP_MODULE_arvatoAfterpayDebitRequiresSalutation'               => 'Bankeinzug erfordert Anrede',
    'SHOP_MODULE_arvatoAfterpayInstallmentsRequiresSalutation'        => 'Ratenzahlung erfordert Anrede',
];
