<?php

$sLangName = 'Deutsch';

$aLang = [
    'charset' => 'UTF-8',

    'ORDER_OVERVIEW_APBIRTHDAY' => 'Geburtstag',
    'ORDER_OVERVIEW_APPHONE'    => 'Telefon',
    'ORDER_OVERVIEW_APFON'      => 'Telefon',
    'ORDER_OVERVIEW_APSSN'      => 'SSN',

    'ORDER_AFTERPAY_ORDERED_AMOUNT'  => 'Bestellte Anzahl',
    'ORDER_AFTERPAY_CAPTURED_AMOUNT' => 'Davon eingezogene Anzahl',
    'ORDER_AFTERPAY_REFUNDED_AMOUNT' => 'Davon erstattete Anzahl',
    'ORDER_AFTERPAY_VOIDED_AMOUNT'   => 'Davon stornierte Anzahl',

    'ORDER_AFTERPAY_TITLE_LISTOFALLITEMS'    => 'Gesamtliste aller bestellter Artikel',
    'ORDER_AFTERPAY_TITLE_CAPTUREPAYMENT'    => 'Reservierte Zahlung einziehen',
    'ORDER_AFTERPAY_TITLE_REFUNDPAYMENT'     => 'Eingezogene Zahlung erstatten',
    'ORDER_AFTERPAY_TITLE_REFUNDPAYMENTFREE' => 'Eingezogene Zahlung erstatten - Frei wählbarer Betrag',
    'ORDER_AFTERPAY_TITLE_VOIDPAYMENT'       => 'Reservierte Zahlung freigeben',

    'ORDER_AFTERPAY_CATEGORY_MAIN_HELP'      => 'Hier wird die Hauptkategorie angezeigt, mit der der Artikel verknüpft wird, falls eine Hauptkategorie in der Datenbank existiert.',
    'ORDER_AFTERPAY_MAIN_CATEGORY'           => 'Hauptkategorie',

    'SHOP_MODULE_GROUP_arvatoAfterpayGeneral'               => 'Allgemeine Einstellungen',
    'SHOP_MODULE_arvatoAfterpayApiDefaultShippingCompany'   => 'Standard Versandunternehmen',
    'HELP_SHOP_MODULE_arvatoAfterpayApiDefaultShippingCompany'   => 'Einstellung für Versand-Capture: Wenn eine Bestellung captured wird, wird auch der Versand erfasst. Dabei kann die Trackingnummer und das verwendete Versandunternehmen angegeben werden. Wird kein Unternehmen angegeben, wird dieses verwendet.',
    'SHOP_MODULE_arvatoAfterpayApiDefaultRefundDescription' => 'Standard Rückerstattungs-Beschreibung',
    'HELP_SHOP_MODULE_arvatoAfterpayApiDefaultRefundDescription' => 'Wird als Default-Beschreibung verwendet, wenn bei einer Rückerstattung keine Beschreibung angegeben wurde.',
    'SHOP_MODULE_arvatoAfterpayRiskChannelType'             => 'Risikosteuerung - ChannelType',
    'HELP_SHOP_MODULE_arvatoAfterpayRiskChannelType'        => 'Relevant für Risiko-Management: Welcher Channel-Typ soll bei Afterpay-Requests angegeben werden. Default "Internet".',
    'SHOP_MODULE_arvatoAfterpayRiskDeliveryType'            => 'Risikosteuerung - DeliveryType',
    'HELP_SHOP_MODULE_arvatoAfterpayRiskDeliveryType'       => 'Relevant für Risiko-Management: Welcher Liefertyp soll bei Afterpay-Requests angegeben werden. Default "Normal".',
    'SHOP_MODULE_arvatoAfterpayManufacturerInDescription'              => 'Marke',
    'HELP_SHOP_MODULE_arvatoAfterpayManufacturerInDescription'         => 'Legt fest, ob der Titel des Herstellers oder Lieferanten des Artikels in den Artikeltitel im Afterpay-Request vorangestellt werden soll.',
    'SHOP_MODULE_arvatoAfterpayManufacturerInDescription_no'           => 'nichts übergeben',
    'SHOP_MODULE_arvatoAfterpayManufacturerInDescription_manufacturer' => 'oxmanufacturer',
    'SHOP_MODULE_arvatoAfterpayManufacturerInDescription_vendor'       => 'oxvendor',
    'SHOP_MODULE_arvatoAfterpayVariantInDescription'                   => 'Variante mit übergeben',
    'HELP_SHOP_MODULE_arvatoAfterpayVariantInDescription'              => 'Legt fest, ob die Variantenbezeichnung des Artikels an den Artikeltitel im Afterpay-Request angehängt werden soll.',
    'SHOP_MODULE_arvatoAfterpayVariantInDescription_yes'               => 'Ja',
    'SHOP_MODULE_arvatoAfterpayVariantInDescription_no'                => 'Nein',
    'SHOP_MODULE_arvatoAfterpayLogo'          => 'Im Checkout angezeigtes Logo',
    'HELP_SHOP_MODULE_arvatoAfterpayLogo'     => 'Die verschiedenen Optionen sind <a target="_blank" href="https://developer.afterpay.io/documentation/logo-and-visual-guidelines/">hier</a> aufgelistet.',
    'SHOP_MODULE_arvatoAfterpayLogo_Checkout' => 'Checkout',
    'SHOP_MODULE_arvatoAfterpayLogo_'         => 'Original',
    'SHOP_MODULE_arvatoAfterpayLogo_Black'    => 'Schwarz',
    'SHOP_MODULE_arvatoAfterpayLogo_White'    => 'Weiß',
    'SHOP_MODULE_arvatoAfterpayLogo_Grey'     => 'Grau',
    'SHOP_MODULE_arvatoAfterpayExcludedArticleNr'     => 'Ausgeschlossene Artikelnummer',
    'HELP_SHOP_MODULE_arvatoAfterpayExcludedArticleNr'     => 'Alle eingetragenen Artikelnummern sind von der Bezahlung mit Afterpay ausgeschlossen. <br> Bitte unbedingt die Artikelnummern mit Komma trennen.',

    'SHOP_MODULE_GROUP_arvatoAfterpayApi' => 'API Einstellungen',
    'SHOP_MODULE_arvatoAfterpayApiUrl'    => 'API Url',

    'SHOP_MODULE_arvatoAfterpayApiKeyDE'            => 'API Schlüssel DE',
    'SHOP_MODULE_arvatoAfterpayApiKeyDEInstallment' => 'API Schlüssel für Ratenkauf DE',
    'SHOP_MODULE_arvatoAfterpayApiKeyAT'            => 'API Schlüssel AT',
    'SHOP_MODULE_arvatoAfterpayApiKeyATInstallment' => 'API Schlüssel für Ratenkauf AT',
    'SHOP_MODULE_arvatoAfterpayApiKeyCH'            => 'API Schlüssel CH',
    'SHOP_MODULE_arvatoAfterpayApiKeyNL'            => 'API Schlüssel NL',
    'SHOP_MODULE_arvatoAfterpayApiKeyBE'            => 'API Schlüssel BE',

    'SHOP_MODULE_arvatoAfterpayApiMode'         => 'API Modus',
    'SHOP_MODULE_arvatoAfterpayApiMode_live'    => 'Live',
    'SHOP_MODULE_arvatoAfterpayApiMode_partner' => 'Partner Test',
    'SHOP_MODULE_arvatoAfterpayApiMode_sandbox' => 'Sandbox',

    'SHOP_MODULE_arvatoAfterpayApiSandboxUrl'              => 'Sandbox API URL',
    'SHOP_MODULE_arvatoAfterpayApiSandboxKeyDE'            => 'Sandbox API Schlüssel DE',
    'SHOP_MODULE_arvatoAfterpayApiSandboxKeyDEInstallment' => 'Sandbox API Schlüssel für Ratenkauf DE',
    'SHOP_MODULE_arvatoAfterpayApiSandboxKeyAT'            => 'Sandbox API Schlüssel AT',
    'SHOP_MODULE_arvatoAfterpayApiSandboxKeyATInstallment' => 'Sandbox API Schlüssel für Ratenkauf AT',
    'SHOP_MODULE_arvatoAfterpayApiSandboxKeyCH'            => 'Sandbox API Schlüssel CH',
    'SHOP_MODULE_arvatoAfterpayApiSandboxKeyNL'            => 'Sandbox API Schlüssel NL',
    'SHOP_MODULE_arvatoAfterpayApiSandboxKeyBE'            => 'Sandbox API Schlüssel BE',

    'SHOP_MODULE_arvatoAfterpayApiPartnerUrl'              => 'Partner Test API URL',
    'SHOP_MODULE_arvatoAfterpayApiPartnerKeyDE'            => 'Partner Test API Schlüssel DE',
    'SHOP_MODULE_arvatoAfterpayApiPartnerKeyDEInstallment' => 'Partner Test API Schlüssel für Ratenkauf DE',
    'SHOP_MODULE_arvatoAfterpayApiPartnerKeyAT'            => 'Partner Test API Schlüssel AT',
    'SHOP_MODULE_arvatoAfterpayApiPartnerKeyATInstallment' => 'Partner Test API Schlüssel für Ratenkauf AT',
    'SHOP_MODULE_arvatoAfterpayApiPartnerKeyCH'            => 'Partner Test API Schlüssel CH',
    'SHOP_MODULE_arvatoAfterpayApiPartnerKeyNL'            => 'Partner Test API Schlüssel NL',
    'SHOP_MODULE_arvatoAfterpayApiPartnerKeyBE'            => 'Partner Test API Schlüssel BE',

    'HELP_SHOP_MODULE_arvatoAfterpayApiMode'             => 'API-Modus: Legt fest, welche der drei Sets an Einstellungen (Live, Sandbox, Partner Test) für Afterpay-API-Requests verwendet werden soll.',
    'HELP_SHOP_MODULE_arvatoAfterpayApiRequestLogging'   => 'Aktiviert Logging für API-Requests und Response. Das Log befindet sich im OXID-Log-Ordner unter dem Namen: AFTERPAY.log',
    'HELP_SHOP_MODULE_arvatoAfterpayApiUrl'              => 'Diese URL wird für Requests an die Afterpay-API verwendet.',
    'HELP_SHOP_MODULE_arvatoAfterpayApiKeyDE'            => 'Dieser API-Key wird für Anfragen für Bestellungen im jeweiligen Land verwendet.',
    'HELP_SHOP_MODULE_arvatoAfterpayApiKeyDEInstallment' => 'Dieser API-Key wird für Anfragen für Ratenzahlungs-Bestellungen im jeweiligen Land verwendet.',

    'SHOP_MODULE_arvatoAfterpayApiRequestLogging'      => 'Api Anfragenprotokollierung',
    'arvato_afterpay_controllers_admin_order_afterpay' => 'AfterPay',
    'AFTERPAY_ONLY_FOR_AFTERPAY_PAYMENT'               => 'Diese Bestellung wurde nicht mit AfterPay bezahlt',
    'ORDER_OVERVIEW_APDEBITBANKACCOUNT'                => 'IBAN',
    'ORDER_OVERVIEW_APINSTALLMENTBANKACCOUNT'          => 'IBAN',
    'ORDER_OVERVIEW_APINSTALLMENTBANKCODE'             => 'BIC',
    'ORDER_OVERVIEW_AFTERPAYINSTALLMENTPROFILEID'      => 'Ratenzahlungsprofil',

    'SHOP_MODULE_GROUP_arvatoAfterpayRequiredFields'          => 'Pflichtfelder',
    'SHOP_MODULE_arvatoAfterpayInvoiceRequiresBirthdate'      => 'Rechnung erfordert Geburtsdatum',
    'SHOP_MODULE_arvatoAfterpayDebitRequiresBirthdate'        => 'Bankeinzug erfordert Geburtsdatum',
    'SHOP_MODULE_arvatoAfterpayInstallmentsRequiresBirthdate' => 'Ratenzahlung erfordert Geburtsdatum',
    'SHOP_MODULE_arvatoAfterpayInvoiceRequiresSSN'            => 'Rechnung erfordert SSN',
    'SHOP_MODULE_arvatoAfterpayDebitRequiresSSN'              => 'Bankeinzug erfordert SSN',
    'SHOP_MODULE_arvatoAfterpayInstallmentsRequiresSSN'       => 'Ratenzahlung erfordert SSN',
    'SHOP_MODULE_arvatoAfterpayInvoiceRequiresFon'            => 'Rechnung erfordert Telefonnummer',
    'SHOP_MODULE_arvatoAfterpayDebitRequiresFon'              => 'Bankeinzug erfordert Telefonnummer',
    'SHOP_MODULE_arvatoAfterpayInstallmentsRequiresFon'       => 'Ratenzahlung erfordert Telefonnummer',

    'SHOP_MODULE_GROUP_arvatoAfterpayProfileTracking'           => 'Profile Tracking (Browsergestützte Betrugserkennung)',
    'SHOP_MODULE_arvatoAfterpayProfileTrackingEnabled'          => 'Profile Tracking',
    'SHOP_MODULE_arvatoAfterpayProfileTrackingEnabled_inactive' => 'Inaktiv',
    'SHOP_MODULE_arvatoAfterpayProfileTrackingEnabled_mandatory'=> 'Pflicht',
    'SHOP_MODULE_arvatoAfterpayProfileTrackingEnabled_optional' => 'Optional',
    'SHOP_MODULE_arvatoAfterpayProfileTrackingUrl'              => 'Profile Tracking URL',
    'SHOP_MODULE_arvatoAfterpayProfileTrackingId'               => 'Profile Tracking Client ID',
    'HELP_SHOP_MODULE_arvatoAfterpayProfileTrackingEnabled'     => 'Aktiviert das Profil-Tracking auf der Zahlungsauswahl-Seite.',
    'HELP_SHOP_MODULE_arvatoAfterpayProfileTrackingUrl'         => 'Profil-Tracking-Requests werden an diese URL geschickt.',
    'HELP_SHOP_MODULE_arvatoAfterpayProfileTrackingId'          => 'Diese ID wird für das Profil-Tracking verwendet.',

    'HELP_ARTICLE_MAIN_AAPPRODUCTGROUP' => 'Definieren Sie die AfterPay-Produktgruppe des Artikels. Lassen Sie das Feld leer, so wird versucht die Produktgruppe anhand der zugeordneten Kategorien zu beziehen. In Klammern steht die übertragene Produktgruppe.',
    'ORDER_AFTERPAY_FORCAPTURENO'       => 'auf Capture-Nummer',
    'ORDER_AFTERPAY_PROMPT_REALLYVOID'     => 'Reservierung freigeben? Das kann nicht rückgängig gemacht werden. Die Bestellung kann danach nicht weiter bearbeitet werden.',
    'ORDER_AFTERPAY_PROMPT_REALLYREFUND'   => 'Zahlung erstatten? Das kann nicht rückgängig gemacht werden.',
    'ORDER_AFTERPAY_TITLE_CAPTUREDELIVERY' => 'Versand erfassen',

    'AFTERPAY_ORDER_ALREADY_VOIDED' => 'Diese Bestellung enthält stornierte Zahlungen und kann deshalb nicht weiter bearbeitet werden.',

    //Menu
    'ARVATOMODULES'                     => 'Arvato Module',
    'AFTERPAY_TITLE'                    => 'Afterpay',
    'AFTERPAY_SETTINGS'                 => 'Einstellungen',
    'AFTERPAY_SAVED'                    => 'Einstellungen wurden gespeichert',
    'AFTERPAY_SAVE_BUTTON'              => 'Speichern',

    'AFTERPAY_COUNTRY_REQUIREDFIELDS_Germany'                     => 'Deutschland',
    'AFTERPAY_COUNTRY_REQUIREDFIELDS_Austria'                     => 'Österreich',
    'AFTERPAY_COUNTRY_REQUIREDFIELDS_Switzerland'                 => 'Schweiz',
    'AFTERPAY_COUNTRY_REQUIREDFIELDS_Netherlands'                 => 'Niederlande',
    'AFTERPAY_COUNTRY_REQUIREDFIELDS_Belgium'                     => 'Belgien',
    'AFTERPAY_COUNTRY_REQUIREDFIELDS_Sweden'                      => 'Schweden',
    'AFTERPAY_COUNTRY_REQUIREDFIELDS_Norway'                      => 'Norwegen',
    'AFTERPAY_COUNTRY_REQUIREDFIELDS_Finland'                     => 'Finnland',
    'AFTERPAY_COUNTRY_REQUIREDFIELDS_Denmark'                     => 'Dänemark',
    'SHOP_MODULE_arvatoAfterpayRequireFieldsExplanation'          => 'Die folgenden Checkboxen legen fest, welche Felder von Kunden im Checkout ausgefüllt werden müssen, damit sie mit der jeweils ausgewählten Zahlungsart fortfahren können.',
    'HELP_SHOP_MODULE_arvatoAfterpayHorizonID'                    => 'Mit der Horizon-ID werden die Links für die Privatsphäre- und AGB-Seiten generiert.',

    'SHOP_MODULE_arvatoAfterpayInvoiceRequiresStreetNumber'             => 'Rechnung erfordert Hausnummer',
    'SHOP_MODULE_arvatoAfterpayDebitRequiresStreetNumber'               => 'Bankeinzug erfordert Hausnummer',
    'SHOP_MODULE_arvatoAfterpayInstallmentsRequiresStreetNumber'        => 'Ratenzahlung erfordert Hausnummer',

    'SHOP_MODULE_arvatoAfterpayInvoiceRequiresSalutation'             => 'Rechnung erfordert Anrede',
    'SHOP_MODULE_arvatoAfterpayDebitRequiresSalutation'               => 'Bankeinzug erfordert Anrede',
    'SHOP_MODULE_arvatoAfterpayInstallmentsRequiresSalutation'        => 'Ratenzahlung erfordert Anrede',

    'SHOP_MODULE_arvatoAfterpayHorizonID'           => 'Horizon-ID',

    'SHOP_MODULE_arvatoAfterpayRequireFields'       => 'Felder',
    'SHOP_MODULE_arvatoAfterpayInvoice'             => 'Rechnung',
    'SHOP_MODULE_arvatoAfterpayDebit'               => 'Bankeinzug',
    'SHOP_MODULE_arvatoAfterpayInstallments'        => 'Ratenzahlung',

    'SHOP_MODULE_arvatoAfterpayRequiresSalutation'        => 'Anrede',
    'SHOP_MODULE_arvatoAfterpayRequiresSSN'               => 'SSN',
    'SHOP_MODULE_arvatoAfterpayRequiresPhone'        => 'Telefonnummer',
    'SHOP_MODULE_arvatoAfterpayRequiresBirthdate'        => 'Geburtsdatum',
    'SHOP_MODULE_arvatoAfterpayRequiresStreetNumber'        => 'Hausnummer',
    'SHOP_MODULE_arvatoAfterpayRequiresPrivacy'        => 'Datenschutz',
    'SHOP_MODULE_arvatoAfterpayRequiresTC'        => 'AGB',

    'ORDER_OVERVIEW_FIRSTNAME'      => 'Vorname',
    'ORDER_OVERVIEW_LASTNAME'       => 'Nachname',
    'ORDER_OVERVIEW_STREET'         => 'Straße',
    'ORDER_OVERVIEW_ZIP'            => 'PLZ',
    'ORDER_OVERVIEW_CITY'           => 'Stadt',
];
